version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: statementflex-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: statementflex
    ports:
      - "58344:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d statementflex"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data: