<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d018feae-e8e1-409c-a637-b4c96a72ef1d</UserSecretsId>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="Hangfire.InMemory" />
    <PackageReference Include="Hangfire.SqlServer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="OpenApiUi" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\StatementFlex.Application\StatementFlex.Application.csproj" />
    <ProjectReference Include="..\StatementFlex.Infrastructure\StatementFlex.Infrastructure.csproj" />
  </ItemGroup>
</Project>
