import { useState, useEffect } from 'react'
import axios from 'axios'

export default function StatementsPanel({ token }) {
  const [downloadLinks, setDownloadLinks] = useState([])
  const [loading, setLoading] = useState(true)
  const [message, setMessage] = useState(null)
  const [downloading, setDownloading] = useState(null)

  useEffect(() => {
    fetchStatements()
  }, [])

  const fetchStatements = async () => {
    try {
      setLoading(true)
      setMessage(null)
      const response = await axios.get('/api/statementflex/statement-list', {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      })

      const links = response.data.downloadLinks || []
      setDownloadLinks(links)

      if (links.length === 0) {
        setMessage({
          type: 'info',
          text: 'No statements available yet. They will appear here after the backend generates them.'
        })
      } else {
        setMessage({
          type: 'success',
          text: `Found ${links.length} statement(s) ready for download`
        })
      }
    } catch (error) {
      console.error('Error:', error)
      setMessage({
        type: 'error',
        text: error.response?.data?.message || 'Failed to fetch statements'
      })
    } finally {
      setLoading(false)
    }
  }

  const downloadStatement = async (index, downloadLink) => {
    try {
      setDownloading(index)
      setMessage(null)

      // Download using the full URL directly
      const response = await axios.get(downloadLink, {
        responseType: 'blob'
      })

      // Create blob and download
      const url = window.URL.createObjectURL(new Blob([response.data]))
      const link = document.createElement('a')
      link.href = url

      // Extract date for filename
      const dateStr = new Date().toISOString().split('T')[0]
      link.setAttribute('download', `statement_${dateStr}.pdf`)

      document.body.appendChild(link)
      link.click()
      link.parentNode.removeChild(link)
      window.URL.revokeObjectURL(url)

      setMessage({
        type: 'success',
        text: 'Statement downloaded successfully! 📥'
      })
    } catch (error) {
      console.error('Download error:', error)
      setMessage({
        type: 'error',
        text: error.response?.data?.message || error.message || 'Failed to download statement'
      })
    } finally {
      setDownloading(null)
    }
  }

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text)
    setMessage({ type: 'success', text: 'Download link copied to clipboard!' })
  }

  return (
    <div className="card">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
        <h2 style={{ margin: 0 }}>📄 Your Statements</h2>
        <button
          className="button button-primary button-small"
          onClick={fetchStatements}
          disabled={loading}
        >
          🔄 Refresh
        </button>
      </div>

      {message && (
        <div className={`alert alert-${message.type}`}>
          {message.text}
        </div>
      )}

      {loading ? (
        <div style={{ textAlign: 'center', padding: '40px 20px' }}>
          <div className="loading" style={{ margin: '0 auto 10px' }}></div>
          <p>Loading statements...</p>
        </div>
      ) : downloadLinks.length === 0 ? (
        <div style={{ textAlign: 'center', padding: '40px 20px', color: '#999' }}>
          <p>📭 No statements available</p>
          <p style={{ fontSize: '0.9em', marginTop: '10px' }}>
            Statements appear here after they are generated by the backend job.
          </p>
        </div>
      ) : (
        <>
          <table className="table">
            <thead>
              <tr>
                <th>Statement Period</th>
                <th>Created</th>
                <th>Token Expires</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {downloadLinks.map((link, index) => {
                const period = new Date(link.statementPeriod).toLocaleDateString('en-US', {
                  year: 'numeric',
                  month: 'long'
                })
                const created = new Date(link.dateCreated).toLocaleString()
                const expires = new Date(link.expiresIn).toLocaleString()

                return (
                  <tr key={index}>
                    <td><strong>{period}</strong></td>
                    <td>{created}</td>
                    <td>{expires}</td>
                    <td>
                      <div className="action-buttons">
                        <button
                          className="button button-primary button-small"
                          onClick={() => downloadStatement(index, link.downloadLink)}
                          disabled={downloading === index}
                          title="Click to download this statement as PDF"
                        >
                          {downloading === index ? '⏳ Downloading...' : '⬇️ Download'}
                        </button>
                        <button
                          className="button button-secondary button-small"
                          onClick={() => copyToClipboard(link.downloadLink)}
                          title="Copy download link to clipboard"
                        >
                          📋 Copy Link
                        </button>
                      </div>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>

          <div style={{ marginTop: '20px', padding: '15px', backgroundColor: '#e3f2fd', borderRadius: '4px', border: '1px solid #2196f3' }}>
            <p style={{ margin: 0, fontSize: '0.9em', color: '#1565c0' }}>
              ℹ️ <strong>Download tokens are valid for 1 hour</strong> and can be used up to 5 times. Each download link is a one-time secure token.
            </p>
          </div>
        </>
      )}
    </div>
  )
}
